.
Signed-off-by: Oguz Ozturk <oguzkaganozt@gmail.com>

diff --git a/docker/tools/scenario-simulator/Dockerfile b/docker/tools/scenario-simulator/Dockerfile
--- a/docker/tools/scenario-simulator/Dockerfile
+++ b/docker/tools/scenario-simulator/Dockerfile
@@ -31,25 +31,25 @@ RUN source /opt/autoware/setup.bash \
     > /rosdep-simulator-exec-depend-packages.txt \
     && cat /rosdep-simulator-exec-depend-packages.txt
 
-### Scenario Simulator
-FROM ghcr.io/autowarefoundation/autoware:core AS scenario-simulator
-SHELL ["/bin/bash", "-o", "pipefail", "-c"]
-ARG ROS_DISTRO
-ARG LIB_DIR
+# ### Scenario Simulator
+# FROM ghcr.io/autowarefoundation/autoware:core AS scenario-simulator
+# SHELL ["/bin/bash", "-o", "pipefail", "-c"]
+# ARG ROS_DISTRO
+# ARG LIB_DIR
 
-COPY --from=builder /opt/autoware /opt/autoware
-COPY --from=builder /rosdep-simulator-exec-depend-packages.txt /tmp/rosdep-simulator-exec-depend-packages.txt
+# COPY --from=builder /opt/autoware /opt/autoware
+# COPY --from=builder /rosdep-simulator-exec-depend-packages.txt /tmp/rosdep-simulator-exec-depend-packages.txt
 
-# hadolint ignore=SC2002
-RUN --mount=type=ssh \
-    --mount=type=cache,target=/var/cache/apt,sharing=locked \
-    apt-get update \
-    # Remove xmlschema and yamale from rosdep packages since we install via pip
-    && sed -i '/\(xmlschema\|yamale\)/d' /tmp/rosdep-simulator-exec-depend-packages.txt \
-    && pip install --no-cache-dir yamale xmlschema \
-    && cat /tmp/rosdep-simulator-exec-depend-packages.txt | xargs apt-get install -y --no-install-recommends \
-    && /autoware/cleanup_system.sh $LIB_DIR $ROS_DISTRO
+# # hadolint ignore=SC2002
+# RUN --mount=type=ssh \
+#     --mount=type=cache,target=/var/cache/apt,sharing=locked \
+#     apt-get update \
+#     # Remove xmlschema and yamale from rosdep packages since we install via pip
+#     && sed -i '/\(xmlschema\|yamale\)/d' /tmp/rosdep-simulator-exec-depend-packages.txt \
+#     && pip install --no-cache-dir yamale xmlschema \
+#     && cat /tmp/rosdep-simulator-exec-depend-packages.txt | xargs apt-get install -y --no-install-recommends \
+#     && /autoware/cleanup_system.sh $LIB_DIR $ROS_DISTRO
 
-COPY docker/tools/scenario-simulator/entrypoint.sh /entrypoint.sh
-RUN chmod +x /entrypoint.sh
-ENTRYPOINT ["/entrypoint.sh"]
+# COPY docker/tools/scenario-simulator/entrypoint.sh /entrypoint.sh
+# RUN chmod +x /entrypoint.sh
+# ENTRYPOINT ["/entrypoint.sh"]
